version: '3.9'
services:
  postgres:
    container_name: currency_db
    image: postgres:16.4
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgrs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d currency_db"]
      interval: 1s
      timeout: 1s
      retries: 5

  redis:
    image: redis:latest
    container_name: currency_redis
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  currency:
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
      args:
        - BUILD_TARGET=./cmd/currency/main.go
    volumes:
      - ./internal/config:/internal/config
      - ./internal/migrations:/internal/migrations
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
      args:
        - BUILD_TARGET=./cmd/gateway/main.go
    volumes:
      - ./internal/config:/internal/config
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - currency

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./internal/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
