service:
  server_port: "8090"

database:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "password"
  name: "currency_db"

kafka:
  host_broker: "kafka:9092"
  host_controller: "kafka:9093"

redis:
  addr: "redis:6379"
  password: "password"
  db: 0

currency:
  url: "http://latest.currency-api.pages.dev/v1/currencies/rub.json"
  target: "usd"
